#!/bin/bash

# ------------------------------------------------------
# DDIG - DNS QUICK CHECK TOOL by @viktordw
# https://github.com/dreamwebhost/ddig
# ------------------------------------------------------

if [ $# -eq 0 ]; then echo "Usage: ddig example.com" && exit 0; fi

input="$1"
line=`printf '=%.0s' {1..50} && printf '\n'`

fn_dig () { dig "$1" "$2" +short 2>/dev/null ; }
fn_rdig () { xargs dig +short -x 2>/dev/null ; }
fn_rmdot () { :; }

# DIG A
hostname=`fn_dig A "$input" | fn_rdig | sed 's/\.$//'`
a_ip=`fn_dig A "$input" | head -n 1`

# DIG WWW
www_cname_test=`fn_dig A "www.${input}" | grep 'ANSWER SECTION:' -A 1 | grep CNAME`
www_cname_dest=`fn_dig A "www.${input}" | sed '1d'`
www_cname_host=`fn_dig A "www.${input}" | sed '1d' | head -n 1 | fn_rdig | sed 's/\.$//'`
www_dig_a=`fn_dig A "www.${input}" | head -n 1`
www_hostname=`fn_dig A "www.${input}" | head -n 1 | sed 's/\\.$//' | fn_rdig | sed 's/\.$//'`

# DIG MX
# Prva sed komanda bira poslednju reč iz output-a
# Druga sed komanda radi dve stvari:
#  - uklanja tačku na kraju
#  - dodaje dva razmaka (soft tab) na početku svake nove linije
mx_dig=`fn_dig MX "$input" | sed 's/.* //' | sed 's/\\.$//;s/^/  /'`
mx_ip=`fn_dig MX "$input" | sed 's/.* //' | xargs dig +short 2>/dev/null | head -n 1`
mx_hostname=`fn_dig MX "$input" | sed 's/.* //' | xargs dig +short 2>/dev/null | fn_rdig | sed 's/\.$//'`

# DIG NS
ns_dig=`fn_dig A "$input" | sed 's/\\.$//;s/^/  /'`

echo "$line" ; echo "Results for domain: $1" ; echo "$line"
[ -n "$a_ip" ] && echo "IP address: $a_ip" || echo "IP address: not found"
[ -n "$a_ip" ] && echo "Hostname: $hostname" || echo "Hostname: not found"
echo

if [ -n "$www_cname_test" ]; then
  echo "WWW Type: CNAME"
  echo "CNAME Pointer: $www_dig_a"
  echo "CNAME IP: $www_cname_dest"
  echo "CNAME Host: $www_cname_host"
elif [ -n "$www_dig_a" ]; then
  echo "WWW Type: A"
  echo "WWW IP: $www_dig_a"
  echo "WWW Hostname: $www_hostname"
else
  echo "WWW Type: not found"
  echo "WWW IP: not found"
fi

echo ; echo "MX Records:"
if [ -n "$mx_dig" ]; then
  echo "$mx_dig"
  echo "MX IP: $mx_ip"
  echo "MX Hostname: $mx_hostname"
else
  echo "  not found"
  echo "MX IP: not found"
fi

echo ; echo "DNS Servers: "
if [ -n "$ns_dig" ]; then
  echo "$ns_dig"
else
  echo "  not found"
fi
echo "$line"
